// flow-typed signature: 8adeb199a2c525d64a8a532b9b45a56c
// flow-typed version: <<STUB>>/loopback-console_v0.2.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loopback-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loopback-console' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loopback-console/context' {
  declare module.exports: any;
}

declare module 'loopback-console/repl' {
  declare module.exports: any;
}

declare module 'loopback-console/test/sample-app/common/models/widget' {
  declare module.exports: any;
}

declare module 'loopback-console/test/sample-app/server/boot/authentication' {
  declare module.exports: any;
}

declare module 'loopback-console/test/sample-app/server/boot/explorer' {
  declare module.exports: any;
}

declare module 'loopback-console/test/sample-app/server/boot/rest-api' {
  declare module.exports: any;
}

declare module 'loopback-console/test/sample-app/server/boot/root' {
  declare module.exports: any;
}

declare module 'loopback-console/test/sample-app/server/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loopback-console/context.js' {
  declare module.exports: $Exports<'loopback-console/context'>;
}
declare module 'loopback-console/index' {
  declare module.exports: $Exports<'loopback-console'>;
}
declare module 'loopback-console/index.js' {
  declare module.exports: $Exports<'loopback-console'>;
}
declare module 'loopback-console/repl.js' {
  declare module.exports: $Exports<'loopback-console/repl'>;
}
declare module 'loopback-console/test/sample-app/common/models/widget.js' {
  declare module.exports: $Exports<'loopback-console/test/sample-app/common/models/widget'>;
}
declare module 'loopback-console/test/sample-app/server/boot/authentication.js' {
  declare module.exports: $Exports<'loopback-console/test/sample-app/server/boot/authentication'>;
}
declare module 'loopback-console/test/sample-app/server/boot/explorer.js' {
  declare module.exports: $Exports<'loopback-console/test/sample-app/server/boot/explorer'>;
}
declare module 'loopback-console/test/sample-app/server/boot/rest-api.js' {
  declare module.exports: $Exports<'loopback-console/test/sample-app/server/boot/rest-api'>;
}
declare module 'loopback-console/test/sample-app/server/boot/root.js' {
  declare module.exports: $Exports<'loopback-console/test/sample-app/server/boot/root'>;
}
declare module 'loopback-console/test/sample-app/server/server.js' {
  declare module.exports: $Exports<'loopback-console/test/sample-app/server/server'>;
}
