// flow-typed signature: 7846bb0f703e004fe15a636404629f29
// flow-typed version: <<STUB>>/loopback-datasource-juggler_v2.50.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loopback-datasource-juggler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loopback-datasource-juggler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loopback-datasource-juggler/examples/app-noschema' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/examples/app' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/examples/datasource-app' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/examples/inclusion' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/examples/load-schemas' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/examples/nesting-schema' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/examples/relations' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/browser.depd' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/connectors/kv-memory' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/connectors/memory' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/connectors/transient' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/dao' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/datasource' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/geo' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/hooks' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/include_utils' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/include' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/introspection' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/jutil' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/kvao/expire' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/kvao/get' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/kvao/index' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/kvao/iterate-keys' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/kvao/keys' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/kvao/set' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/kvao/ttl' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/list' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/mixins' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/model-builder' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/model-definition' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/model' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/observer' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/relation-definition' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/relations' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/scope' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/transaction' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/types' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/utils' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/lib/validations' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/support/describe-operation-hooks' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/async-observer.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/basic-querying.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/common_test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/common.batch' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/crud-with-options.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/CustomTypeForeignKey.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/datasource.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/datatype.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/default-scope.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/defaults.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/discovery.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/events' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/geo.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/helpers/context-test-helpers' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/helpers/hook-monitor' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/helpers/uid-generator' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/hooks.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/include_util.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/include.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/init' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/introspection.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/json.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/kv-memory' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/kvao.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/kvao/_helpers' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/kvao/expire.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/kvao/get-set.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/kvao/iterate-keys.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/kvao/keys.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/kvao/ttl.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/loopback-data.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/loopback-dl.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/manipulation.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/memory.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/mixins.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/model-definition.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-many-create.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-many-destroy.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-many-update-by-id.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-one-create.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-one-destroy.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-one-update.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/operation-hooks.suite/index' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/optional-validation.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/persistence-hooks.suite' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/relations.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/schema.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/scope.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/spec_helper' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/transient.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/util.test' {
  declare module.exports: any;
}

declare module 'loopback-datasource-juggler/test/validations.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loopback-datasource-juggler/examples/app-noschema.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/examples/app-noschema'>;
}
declare module 'loopback-datasource-juggler/examples/app.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/examples/app'>;
}
declare module 'loopback-datasource-juggler/examples/datasource-app.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/examples/datasource-app'>;
}
declare module 'loopback-datasource-juggler/examples/inclusion.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/examples/inclusion'>;
}
declare module 'loopback-datasource-juggler/examples/load-schemas.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/examples/load-schemas'>;
}
declare module 'loopback-datasource-juggler/examples/nesting-schema.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/examples/nesting-schema'>;
}
declare module 'loopback-datasource-juggler/examples/relations.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/examples/relations'>;
}
declare module 'loopback-datasource-juggler/index' {
  declare module.exports: $Exports<'loopback-datasource-juggler'>;
}
declare module 'loopback-datasource-juggler/index.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler'>;
}
declare module 'loopback-datasource-juggler/lib/browser.depd.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/browser.depd'>;
}
declare module 'loopback-datasource-juggler/lib/connectors/kv-memory.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/connectors/kv-memory'>;
}
declare module 'loopback-datasource-juggler/lib/connectors/memory.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/connectors/memory'>;
}
declare module 'loopback-datasource-juggler/lib/connectors/transient.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/connectors/transient'>;
}
declare module 'loopback-datasource-juggler/lib/dao.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/dao'>;
}
declare module 'loopback-datasource-juggler/lib/datasource.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/datasource'>;
}
declare module 'loopback-datasource-juggler/lib/geo.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/geo'>;
}
declare module 'loopback-datasource-juggler/lib/hooks.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/hooks'>;
}
declare module 'loopback-datasource-juggler/lib/include_utils.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/include_utils'>;
}
declare module 'loopback-datasource-juggler/lib/include.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/include'>;
}
declare module 'loopback-datasource-juggler/lib/introspection.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/introspection'>;
}
declare module 'loopback-datasource-juggler/lib/jutil.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/jutil'>;
}
declare module 'loopback-datasource-juggler/lib/kvao/expire.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/kvao/expire'>;
}
declare module 'loopback-datasource-juggler/lib/kvao/get.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/kvao/get'>;
}
declare module 'loopback-datasource-juggler/lib/kvao/index.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/kvao/index'>;
}
declare module 'loopback-datasource-juggler/lib/kvao/iterate-keys.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/kvao/iterate-keys'>;
}
declare module 'loopback-datasource-juggler/lib/kvao/keys.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/kvao/keys'>;
}
declare module 'loopback-datasource-juggler/lib/kvao/set.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/kvao/set'>;
}
declare module 'loopback-datasource-juggler/lib/kvao/ttl.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/kvao/ttl'>;
}
declare module 'loopback-datasource-juggler/lib/list.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/list'>;
}
declare module 'loopback-datasource-juggler/lib/mixins.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/mixins'>;
}
declare module 'loopback-datasource-juggler/lib/model-builder.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/model-builder'>;
}
declare module 'loopback-datasource-juggler/lib/model-definition.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/model-definition'>;
}
declare module 'loopback-datasource-juggler/lib/model.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/model'>;
}
declare module 'loopback-datasource-juggler/lib/observer.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/observer'>;
}
declare module 'loopback-datasource-juggler/lib/relation-definition.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/relation-definition'>;
}
declare module 'loopback-datasource-juggler/lib/relations.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/relations'>;
}
declare module 'loopback-datasource-juggler/lib/scope.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/scope'>;
}
declare module 'loopback-datasource-juggler/lib/transaction.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/transaction'>;
}
declare module 'loopback-datasource-juggler/lib/types.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/types'>;
}
declare module 'loopback-datasource-juggler/lib/utils.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/utils'>;
}
declare module 'loopback-datasource-juggler/lib/validations.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/lib/validations'>;
}
declare module 'loopback-datasource-juggler/support/describe-operation-hooks.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/support/describe-operation-hooks'>;
}
declare module 'loopback-datasource-juggler/test/async-observer.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/async-observer.test'>;
}
declare module 'loopback-datasource-juggler/test/basic-querying.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/basic-querying.test'>;
}
declare module 'loopback-datasource-juggler/test/common_test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/common_test'>;
}
declare module 'loopback-datasource-juggler/test/common.batch.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/common.batch'>;
}
declare module 'loopback-datasource-juggler/test/crud-with-options.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/crud-with-options.test'>;
}
declare module 'loopback-datasource-juggler/test/CustomTypeForeignKey.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/CustomTypeForeignKey.test'>;
}
declare module 'loopback-datasource-juggler/test/datasource.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/datasource.test'>;
}
declare module 'loopback-datasource-juggler/test/datatype.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/datatype.test'>;
}
declare module 'loopback-datasource-juggler/test/default-scope.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/default-scope.test'>;
}
declare module 'loopback-datasource-juggler/test/defaults.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/defaults.test'>;
}
declare module 'loopback-datasource-juggler/test/discovery.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/discovery.test'>;
}
declare module 'loopback-datasource-juggler/test/events.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/events'>;
}
declare module 'loopback-datasource-juggler/test/geo.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/geo.test'>;
}
declare module 'loopback-datasource-juggler/test/helpers/context-test-helpers.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/helpers/context-test-helpers'>;
}
declare module 'loopback-datasource-juggler/test/helpers/hook-monitor.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/helpers/hook-monitor'>;
}
declare module 'loopback-datasource-juggler/test/helpers/uid-generator.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/helpers/uid-generator'>;
}
declare module 'loopback-datasource-juggler/test/hooks.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/hooks.test'>;
}
declare module 'loopback-datasource-juggler/test/include_util.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/include_util.test'>;
}
declare module 'loopback-datasource-juggler/test/include.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/include.test'>;
}
declare module 'loopback-datasource-juggler/test/init.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/init'>;
}
declare module 'loopback-datasource-juggler/test/introspection.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/introspection.test'>;
}
declare module 'loopback-datasource-juggler/test/json.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/json.test'>;
}
declare module 'loopback-datasource-juggler/test/kv-memory.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/kv-memory'>;
}
declare module 'loopback-datasource-juggler/test/kvao.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/kvao.suite'>;
}
declare module 'loopback-datasource-juggler/test/kvao/_helpers.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/kvao/_helpers'>;
}
declare module 'loopback-datasource-juggler/test/kvao/expire.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/kvao/expire.suite'>;
}
declare module 'loopback-datasource-juggler/test/kvao/get-set.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/kvao/get-set.suite'>;
}
declare module 'loopback-datasource-juggler/test/kvao/iterate-keys.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/kvao/iterate-keys.suite'>;
}
declare module 'loopback-datasource-juggler/test/kvao/keys.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/kvao/keys.suite'>;
}
declare module 'loopback-datasource-juggler/test/kvao/ttl.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/kvao/ttl.suite'>;
}
declare module 'loopback-datasource-juggler/test/loopback-data.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/loopback-data.test'>;
}
declare module 'loopback-datasource-juggler/test/loopback-dl.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/loopback-dl.test'>;
}
declare module 'loopback-datasource-juggler/test/manipulation.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/manipulation.test'>;
}
declare module 'loopback-datasource-juggler/test/memory.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/memory.test'>;
}
declare module 'loopback-datasource-juggler/test/mixins.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/mixins.test'>;
}
declare module 'loopback-datasource-juggler/test/model-definition.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/model-definition.test'>;
}
declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-many-create.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/operation-hooks.suite/embeds-many-create.suite'>;
}
declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-many-destroy.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/operation-hooks.suite/embeds-many-destroy.suite'>;
}
declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-many-update-by-id.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/operation-hooks.suite/embeds-many-update-by-id.suite'>;
}
declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-one-create.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/operation-hooks.suite/embeds-one-create.suite'>;
}
declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-one-destroy.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/operation-hooks.suite/embeds-one-destroy.suite'>;
}
declare module 'loopback-datasource-juggler/test/operation-hooks.suite/embeds-one-update.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/operation-hooks.suite/embeds-one-update.suite'>;
}
declare module 'loopback-datasource-juggler/test/operation-hooks.suite/index.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/operation-hooks.suite/index'>;
}
declare module 'loopback-datasource-juggler/test/optional-validation.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/optional-validation.test'>;
}
declare module 'loopback-datasource-juggler/test/persistence-hooks.suite.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/persistence-hooks.suite'>;
}
declare module 'loopback-datasource-juggler/test/relations.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/relations.test'>;
}
declare module 'loopback-datasource-juggler/test/schema.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/schema.test'>;
}
declare module 'loopback-datasource-juggler/test/scope.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/scope.test'>;
}
declare module 'loopback-datasource-juggler/test/spec_helper.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/spec_helper'>;
}
declare module 'loopback-datasource-juggler/test/transient.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/transient.test'>;
}
declare module 'loopback-datasource-juggler/test/util.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/util.test'>;
}
declare module 'loopback-datasource-juggler/test/validations.test.js' {
  declare module.exports: $Exports<'loopback-datasource-juggler/test/validations.test'>;
}
