// flow-typed signature: d09f6eb45bf6ff8d6562f087ff4b23a1
// flow-typed version: <<STUB>>/loopback-component-explorer_v2.6.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loopback-component-explorer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loopback-component-explorer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loopback-component-explorer/example/hidden' {
  declare module.exports: any;
}

declare module 'loopback-component-explorer/example/simple' {
  declare module.exports: any;
}

declare module 'loopback-component-explorer/lib/url-join' {
  declare module.exports: any;
}

declare module 'loopback-component-explorer/public/lib/loadSwaggerUI' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loopback-component-explorer/example/hidden.js' {
  declare module.exports: $Exports<'loopback-component-explorer/example/hidden'>;
}
declare module 'loopback-component-explorer/example/simple.js' {
  declare module.exports: $Exports<'loopback-component-explorer/example/simple'>;
}
declare module 'loopback-component-explorer/index' {
  declare module.exports: $Exports<'loopback-component-explorer'>;
}
declare module 'loopback-component-explorer/index.js' {
  declare module.exports: $Exports<'loopback-component-explorer'>;
}
declare module 'loopback-component-explorer/lib/url-join.js' {
  declare module.exports: $Exports<'loopback-component-explorer/lib/url-join'>;
}
declare module 'loopback-component-explorer/public/lib/loadSwaggerUI.js' {
  declare module.exports: $Exports<'loopback-component-explorer/public/lib/loadSwaggerUI'>;
}
