// flow-typed signature: db1b1dfd3b75dd259a00acb3cacd90cf
// flow-typed version: <<STUB>>/loopback_v2.33.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loopback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loopback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loopback/common/models/access-token' {
  declare module.exports: any;
}

declare module 'loopback/common/models/acl' {
  declare module.exports: any;
}

declare module 'loopback/common/models/application' {
  declare module.exports: any;
}

declare module 'loopback/common/models/change' {
  declare module.exports: any;
}

declare module 'loopback/common/models/checkpoint' {
  declare module.exports: any;
}

declare module 'loopback/common/models/email' {
  declare module.exports: any;
}

declare module 'loopback/common/models/key-value-model' {
  declare module.exports: any;
}

declare module 'loopback/common/models/role-mapping' {
  declare module.exports: any;
}

declare module 'loopback/common/models/role' {
  declare module.exports: any;
}

declare module 'loopback/common/models/scope' {
  declare module.exports: any;
}

declare module 'loopback/common/models/user' {
  declare module.exports: any;
}

declare module 'loopback/example/client-server/client' {
  declare module.exports: any;
}

declare module 'loopback/example/client-server/models' {
  declare module.exports: any;
}

declare module 'loopback/example/client-server/server' {
  declare module.exports: any;
}

declare module 'loopback/example/colors/app' {
  declare module.exports: any;
}

declare module 'loopback/example/context/app' {
  declare module.exports: any;
}

declare module 'loopback/example/mobile-models/app' {
  declare module.exports: any;
}

declare module 'loopback/example/replication/app' {
  declare module.exports: any;
}

declare module 'loopback/example/simple-data-source/app' {
  declare module.exports: any;
}

declare module 'loopback/Gruntfile' {
  declare module.exports: any;
}

declare module 'loopback/lib/access-context' {
  declare module.exports: any;
}

declare module 'loopback/lib/application' {
  declare module.exports: any;
}

declare module 'loopback/lib/browser-express' {
  declare module.exports: any;
}

declare module 'loopback/lib/builtin-models' {
  declare module.exports: any;
}

declare module 'loopback/lib/connectors/base-connector' {
  declare module.exports: any;
}

declare module 'loopback/lib/connectors/mail' {
  declare module.exports: any;
}

declare module 'loopback/lib/connectors/memory' {
  declare module.exports: any;
}

declare module 'loopback/lib/current-context' {
  declare module.exports: any;
}

declare module 'loopback/lib/express-middleware' {
  declare module.exports: any;
}

declare module 'loopback/lib/loopback' {
  declare module.exports: any;
}

declare module 'loopback/lib/model' {
  declare module.exports: any;
}

declare module 'loopback/lib/persisted-model' {
  declare module.exports: any;
}

declare module 'loopback/lib/registry' {
  declare module.exports: any;
}

declare module 'loopback/lib/runtime' {
  declare module.exports: any;
}

declare module 'loopback/lib/server-app' {
  declare module.exports: any;
}

declare module 'loopback/lib/utils' {
  declare module.exports: any;
}

declare module 'loopback/server/middleware/context' {
  declare module.exports: any;
}

declare module 'loopback/server/middleware/error-handler' {
  declare module.exports: any;
}

declare module 'loopback/server/middleware/favicon' {
  declare module.exports: any;
}

declare module 'loopback/server/middleware/rest' {
  declare module.exports: any;
}

declare module 'loopback/server/middleware/static' {
  declare module.exports: any;
}

declare module 'loopback/server/middleware/status' {
  declare module.exports: any;
}

declare module 'loopback/server/middleware/token' {
  declare module.exports: any;
}

declare module 'loopback/server/middleware/url-not-found' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loopback/common/models/access-token.js' {
  declare module.exports: $Exports<'loopback/common/models/access-token'>;
}
declare module 'loopback/common/models/acl.js' {
  declare module.exports: $Exports<'loopback/common/models/acl'>;
}
declare module 'loopback/common/models/application.js' {
  declare module.exports: $Exports<'loopback/common/models/application'>;
}
declare module 'loopback/common/models/change.js' {
  declare module.exports: $Exports<'loopback/common/models/change'>;
}
declare module 'loopback/common/models/checkpoint.js' {
  declare module.exports: $Exports<'loopback/common/models/checkpoint'>;
}
declare module 'loopback/common/models/email.js' {
  declare module.exports: $Exports<'loopback/common/models/email'>;
}
declare module 'loopback/common/models/key-value-model.js' {
  declare module.exports: $Exports<'loopback/common/models/key-value-model'>;
}
declare module 'loopback/common/models/role-mapping.js' {
  declare module.exports: $Exports<'loopback/common/models/role-mapping'>;
}
declare module 'loopback/common/models/role.js' {
  declare module.exports: $Exports<'loopback/common/models/role'>;
}
declare module 'loopback/common/models/scope.js' {
  declare module.exports: $Exports<'loopback/common/models/scope'>;
}
declare module 'loopback/common/models/user.js' {
  declare module.exports: $Exports<'loopback/common/models/user'>;
}
declare module 'loopback/example/client-server/client.js' {
  declare module.exports: $Exports<'loopback/example/client-server/client'>;
}
declare module 'loopback/example/client-server/models.js' {
  declare module.exports: $Exports<'loopback/example/client-server/models'>;
}
declare module 'loopback/example/client-server/server.js' {
  declare module.exports: $Exports<'loopback/example/client-server/server'>;
}
declare module 'loopback/example/colors/app.js' {
  declare module.exports: $Exports<'loopback/example/colors/app'>;
}
declare module 'loopback/example/context/app.js' {
  declare module.exports: $Exports<'loopback/example/context/app'>;
}
declare module 'loopback/example/mobile-models/app.js' {
  declare module.exports: $Exports<'loopback/example/mobile-models/app'>;
}
declare module 'loopback/example/replication/app.js' {
  declare module.exports: $Exports<'loopback/example/replication/app'>;
}
declare module 'loopback/example/simple-data-source/app.js' {
  declare module.exports: $Exports<'loopback/example/simple-data-source/app'>;
}
declare module 'loopback/Gruntfile.js' {
  declare module.exports: $Exports<'loopback/Gruntfile'>;
}
declare module 'loopback/index' {
  declare module.exports: $Exports<'loopback'>;
}
declare module 'loopback/index.js' {
  declare module.exports: $Exports<'loopback'>;
}
declare module 'loopback/lib/access-context.js' {
  declare module.exports: $Exports<'loopback/lib/access-context'>;
}
declare module 'loopback/lib/application.js' {
  declare module.exports: $Exports<'loopback/lib/application'>;
}
declare module 'loopback/lib/browser-express.js' {
  declare module.exports: $Exports<'loopback/lib/browser-express'>;
}
declare module 'loopback/lib/builtin-models.js' {
  declare module.exports: $Exports<'loopback/lib/builtin-models'>;
}
declare module 'loopback/lib/connectors/base-connector.js' {
  declare module.exports: $Exports<'loopback/lib/connectors/base-connector'>;
}
declare module 'loopback/lib/connectors/mail.js' {
  declare module.exports: $Exports<'loopback/lib/connectors/mail'>;
}
declare module 'loopback/lib/connectors/memory.js' {
  declare module.exports: $Exports<'loopback/lib/connectors/memory'>;
}
declare module 'loopback/lib/current-context.js' {
  declare module.exports: $Exports<'loopback/lib/current-context'>;
}
declare module 'loopback/lib/express-middleware.js' {
  declare module.exports: $Exports<'loopback/lib/express-middleware'>;
}
declare module 'loopback/lib/loopback.js' {
  declare module.exports: $Exports<'loopback/lib/loopback'>;
}
declare module 'loopback/lib/model.js' {
  declare module.exports: $Exports<'loopback/lib/model'>;
}
declare module 'loopback/lib/persisted-model.js' {
  declare module.exports: $Exports<'loopback/lib/persisted-model'>;
}
declare module 'loopback/lib/registry.js' {
  declare module.exports: $Exports<'loopback/lib/registry'>;
}
declare module 'loopback/lib/runtime.js' {
  declare module.exports: $Exports<'loopback/lib/runtime'>;
}
declare module 'loopback/lib/server-app.js' {
  declare module.exports: $Exports<'loopback/lib/server-app'>;
}
declare module 'loopback/lib/utils.js' {
  declare module.exports: $Exports<'loopback/lib/utils'>;
}
declare module 'loopback/server/middleware/context.js' {
  declare module.exports: $Exports<'loopback/server/middleware/context'>;
}
declare module 'loopback/server/middleware/error-handler.js' {
  declare module.exports: $Exports<'loopback/server/middleware/error-handler'>;
}
declare module 'loopback/server/middleware/favicon.js' {
  declare module.exports: $Exports<'loopback/server/middleware/favicon'>;
}
declare module 'loopback/server/middleware/rest.js' {
  declare module.exports: $Exports<'loopback/server/middleware/rest'>;
}
declare module 'loopback/server/middleware/static.js' {
  declare module.exports: $Exports<'loopback/server/middleware/static'>;
}
declare module 'loopback/server/middleware/status.js' {
  declare module.exports: $Exports<'loopback/server/middleware/status'>;
}
declare module 'loopback/server/middleware/token.js' {
  declare module.exports: $Exports<'loopback/server/middleware/token'>;
}
declare module 'loopback/server/middleware/url-not-found.js' {
  declare module.exports: $Exports<'loopback/server/middleware/url-not-found'>;
}
