// flow-typed signature: f455ecb826da44b67d416ca37ac5002d
// flow-typed version: <<STUB>>/loopback-connector-mongodb_v1.15.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loopback-connector-mongodb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loopback-connector-mongodb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loopback-connector-mongodb/benchmarks/index' {
  declare module.exports: any;
}

declare module 'loopback-connector-mongodb/example/model' {
  declare module.exports: any;
}

declare module 'loopback-connector-mongodb/leak-detection/fixtures/todo' {
  declare module.exports: any;
}

declare module 'loopback-connector-mongodb/leak-detection/globals' {
  declare module.exports: any;
}

declare module 'loopback-connector-mongodb/leak-detection/leak-detector.test' {
  declare module.exports: any;
}

declare module 'loopback-connector-mongodb/leak-detection/mongodb.test' {
  declare module.exports: any;
}

declare module 'loopback-connector-mongodb/lib/mongodb' {
  declare module.exports: any;
}

declare module 'loopback-connector-mongodb/lib/test-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loopback-connector-mongodb/benchmarks/index.js' {
  declare module.exports: $Exports<'loopback-connector-mongodb/benchmarks/index'>;
}
declare module 'loopback-connector-mongodb/example/model.js' {
  declare module.exports: $Exports<'loopback-connector-mongodb/example/model'>;
}
declare module 'loopback-connector-mongodb/index' {
  declare module.exports: $Exports<'loopback-connector-mongodb'>;
}
declare module 'loopback-connector-mongodb/index.js' {
  declare module.exports: $Exports<'loopback-connector-mongodb'>;
}
declare module 'loopback-connector-mongodb/leak-detection/fixtures/todo.js' {
  declare module.exports: $Exports<'loopback-connector-mongodb/leak-detection/fixtures/todo'>;
}
declare module 'loopback-connector-mongodb/leak-detection/globals.js' {
  declare module.exports: $Exports<'loopback-connector-mongodb/leak-detection/globals'>;
}
declare module 'loopback-connector-mongodb/leak-detection/leak-detector.test.js' {
  declare module.exports: $Exports<'loopback-connector-mongodb/leak-detection/leak-detector.test'>;
}
declare module 'loopback-connector-mongodb/leak-detection/mongodb.test.js' {
  declare module.exports: $Exports<'loopback-connector-mongodb/leak-detection/mongodb.test'>;
}
declare module 'loopback-connector-mongodb/lib/mongodb.js' {
  declare module.exports: $Exports<'loopback-connector-mongodb/lib/mongodb'>;
}
declare module 'loopback-connector-mongodb/lib/test-utils.js' {
  declare module.exports: $Exports<'loopback-connector-mongodb/lib/test-utils'>;
}
