// flow-typed signature: 8a85e7b4b70b4d048e463ce29ad47b7d
// flow-typed version: <<STUB>>/messenger-bot_v2.3.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'messenger-bot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'messenger-bot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'messenger-bot/example/echo-express' {
  declare module.exports: any;
}

declare module 'messenger-bot/example/echo' {
  declare module.exports: any;
}

declare module 'messenger-bot/example/recognize-music/index' {
  declare module.exports: any;
}

declare module 'messenger-bot/example/recognize-music/recognize' {
  declare module.exports: any;
}

declare module 'messenger-bot/test/basic' {
  declare module.exports: any;
}

declare module 'messenger-bot/test/get-profile' {
  declare module.exports: any;
}

declare module 'messenger-bot/test/middleware-get' {
  declare module.exports: any;
}

declare module 'messenger-bot/test/middleware-post' {
  declare module.exports: any;
}

declare module 'messenger-bot/test/send-message' {
  declare module.exports: any;
}

// Filename aliases
declare module 'messenger-bot/example/echo-express.js' {
  declare module.exports: $Exports<'messenger-bot/example/echo-express'>;
}
declare module 'messenger-bot/example/echo.js' {
  declare module.exports: $Exports<'messenger-bot/example/echo'>;
}
declare module 'messenger-bot/example/recognize-music/index.js' {
  declare module.exports: $Exports<'messenger-bot/example/recognize-music/index'>;
}
declare module 'messenger-bot/example/recognize-music/recognize.js' {
  declare module.exports: $Exports<'messenger-bot/example/recognize-music/recognize'>;
}
declare module 'messenger-bot/index' {
  declare module.exports: $Exports<'messenger-bot'>;
}
declare module 'messenger-bot/index.js' {
  declare module.exports: $Exports<'messenger-bot'>;
}
declare module 'messenger-bot/test/basic.js' {
  declare module.exports: $Exports<'messenger-bot/test/basic'>;
}
declare module 'messenger-bot/test/get-profile.js' {
  declare module.exports: $Exports<'messenger-bot/test/get-profile'>;
}
declare module 'messenger-bot/test/middleware-get.js' {
  declare module.exports: $Exports<'messenger-bot/test/middleware-get'>;
}
declare module 'messenger-bot/test/middleware-post.js' {
  declare module.exports: $Exports<'messenger-bot/test/middleware-post'>;
}
declare module 'messenger-bot/test/send-message.js' {
  declare module.exports: $Exports<'messenger-bot/test/send-message'>;
}
