// flow-typed signature: 8e27f9dfe5f87c3f4fa80d4b8e9c93b1
// flow-typed version: <<STUB>>/node-tvdb_v2.0.12/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-tvdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-tvdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-tvdb/test/episode-by-airdate' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/episode' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/episodes-by-id' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/find-actors' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/find-banners' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/language' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/module' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/search-by-id' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/search-by-name' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/search-by-remote' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/time' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/update' {
  declare module.exports: any;
}

declare module 'node-tvdb/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-tvdb/index' {
  declare module.exports: $Exports<'node-tvdb'>;
}
declare module 'node-tvdb/index.js' {
  declare module.exports: $Exports<'node-tvdb'>;
}
declare module 'node-tvdb/test/episode-by-airdate.js' {
  declare module.exports: $Exports<'node-tvdb/test/episode-by-airdate'>;
}
declare module 'node-tvdb/test/episode.js' {
  declare module.exports: $Exports<'node-tvdb/test/episode'>;
}
declare module 'node-tvdb/test/episodes-by-id.js' {
  declare module.exports: $Exports<'node-tvdb/test/episodes-by-id'>;
}
declare module 'node-tvdb/test/find-actors.js' {
  declare module.exports: $Exports<'node-tvdb/test/find-actors'>;
}
declare module 'node-tvdb/test/find-banners.js' {
  declare module.exports: $Exports<'node-tvdb/test/find-banners'>;
}
declare module 'node-tvdb/test/language.js' {
  declare module.exports: $Exports<'node-tvdb/test/language'>;
}
declare module 'node-tvdb/test/module.js' {
  declare module.exports: $Exports<'node-tvdb/test/module'>;
}
declare module 'node-tvdb/test/search-by-id.js' {
  declare module.exports: $Exports<'node-tvdb/test/search-by-id'>;
}
declare module 'node-tvdb/test/search-by-name.js' {
  declare module.exports: $Exports<'node-tvdb/test/search-by-name'>;
}
declare module 'node-tvdb/test/search-by-remote.js' {
  declare module.exports: $Exports<'node-tvdb/test/search-by-remote'>;
}
declare module 'node-tvdb/test/time.js' {
  declare module.exports: $Exports<'node-tvdb/test/time'>;
}
declare module 'node-tvdb/test/update.js' {
  declare module.exports: $Exports<'node-tvdb/test/update'>;
}
declare module 'node-tvdb/test/utils.js' {
  declare module.exports: $Exports<'node-tvdb/test/utils'>;
}
