// flow-typed signature: 23375b6a9705fb5add77d236c11b1aa4
// flow-typed version: <<STUB>>/raven_v1.1.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raven'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'raven' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raven/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'raven/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'raven/lib/breadcrumbs' {
  declare module.exports: any;
}

declare module 'raven/lib/client' {
  declare module.exports: any;
}

declare module 'raven/lib/middleware/connect' {
  declare module.exports: any;
}

declare module 'raven/lib/parsers' {
  declare module.exports: any;
}

declare module 'raven/lib/transports' {
  declare module.exports: any;
}

declare module 'raven/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raven/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'raven/coverage/lcov-report/prettify'>;
}
declare module 'raven/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'raven/coverage/lcov-report/sorter'>;
}
declare module 'raven/index' {
  declare module.exports: $Exports<'raven'>;
}
declare module 'raven/index.js' {
  declare module.exports: $Exports<'raven'>;
}
declare module 'raven/lib/breadcrumbs.js' {
  declare module.exports: $Exports<'raven/lib/breadcrumbs'>;
}
declare module 'raven/lib/client.js' {
  declare module.exports: $Exports<'raven/lib/client'>;
}
declare module 'raven/lib/middleware/connect.js' {
  declare module.exports: $Exports<'raven/lib/middleware/connect'>;
}
declare module 'raven/lib/parsers.js' {
  declare module.exports: $Exports<'raven/lib/parsers'>;
}
declare module 'raven/lib/transports.js' {
  declare module.exports: $Exports<'raven/lib/transports'>;
}
declare module 'raven/lib/utils.js' {
  declare module.exports: $Exports<'raven/lib/utils'>;
}
