// flow-typed signature: 2cf5775b507cacfe4cade3f86b70df16
// flow-typed version: <<STUB>>/strong-error-handler_v1.1.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strong-error-handler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'strong-error-handler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'strong-error-handler/lib/clone' {
  declare module.exports: any;
}

declare module 'strong-error-handler/lib/content-negotiation' {
  declare module.exports: any;
}

declare module 'strong-error-handler/lib/data-builder' {
  declare module.exports: any;
}

declare module 'strong-error-handler/lib/handler' {
  declare module.exports: any;
}

declare module 'strong-error-handler/lib/logger' {
  declare module.exports: any;
}

declare module 'strong-error-handler/lib/send-html' {
  declare module.exports: any;
}

declare module 'strong-error-handler/lib/send-json' {
  declare module.exports: any;
}

// Filename aliases
declare module 'strong-error-handler/lib/clone.js' {
  declare module.exports: $Exports<'strong-error-handler/lib/clone'>;
}
declare module 'strong-error-handler/lib/content-negotiation.js' {
  declare module.exports: $Exports<'strong-error-handler/lib/content-negotiation'>;
}
declare module 'strong-error-handler/lib/data-builder.js' {
  declare module.exports: $Exports<'strong-error-handler/lib/data-builder'>;
}
declare module 'strong-error-handler/lib/handler.js' {
  declare module.exports: $Exports<'strong-error-handler/lib/handler'>;
}
declare module 'strong-error-handler/lib/logger.js' {
  declare module.exports: $Exports<'strong-error-handler/lib/logger'>;
}
declare module 'strong-error-handler/lib/send-html.js' {
  declare module.exports: $Exports<'strong-error-handler/lib/send-html'>;
}
declare module 'strong-error-handler/lib/send-json.js' {
  declare module.exports: $Exports<'strong-error-handler/lib/send-json'>;
}
